### ISSUE TITLE
Support on browser

### ISSUE THREAD

**Issue by chiiaik** [noodlefrenzy/node-amqp10-transport-ws#7]
Thank you for making this library, it works well on Nodejs!

I'm currently trying to make it work on browser by replacing the socket with WebSocket API. However, the web socket connection is closed with code 1000, as soon as the SASL negotiation starts. 

Below are the logs I got:
```
connecting to: wss://saskeyname:saskey@sbnamespace.servicebus.windows.net:443/$servicebus/websocket   connection.js:293
stateChange: DISCONNECTED => START , reason: connect    Connection.js:131
onopen: readyState: 1
Sending Header 414d515003010000.   connection.js:363
stateChange: START => IN_SASL , reason: connected  connection.js:293
onclose: code: 1000, reason: "", readyState: 3    Connection.js:141
on(end)   connection.js:519
disconnected   amqp_client.js:177
stateChange: IN_SASL => DISCONNECTED , reason: terminated   connection.js:293

Do you have plan to make it work on browser?

**Comment by pierreca** [comment]
There is no plan to make this amqp library work in the browser. you can take a look at [grs/rhea](https://github.com/grs/rhea) though as I believe it does support execution in the browser.
